### ISSUE TITLE
Easier API to get project options

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ionide/dotnet-proj-info#16]
Fable is using Dotnet.ProjInfo and it's working really well, thank you! However, I'm concerned that I need to keep [this file](https://github.com/fable-compiler/Fable/blob/f8457dc6ff3208af85166a14da0feb520927bc55/src/dotnet/dotnet-fable/ProjectCoreCracker.fs) in my repo. It's mainly copied from Ionide (or FSAC, I don't remember) and it's also working fine. But the code is not trivial and has some slight modifications, so I'm afraid it can easily break and/or become outdated soon and it won't be easy to keep it up-to-date.

It'd be great if there was a simple function exposed by Dotnet.ProjInfo to which I could pass the .fsproj file path and get the Project options without the extra boilerplate.

**Comment by alfonsogarciacaro** [comment]
@enricosada Any thoughts on this? :)

**Comment by enricosada** [comment]
pratically that file does two things:

- navigate the projects (so all p2p references) based on target framework
- convert to use default ProjectCracker options (used by FCS)

i think i can add these as feature to this library:

- put the first thing (navigate p2p) inside this library directly.
- use a builtin type, who can be easy mapped to FCS type as needed
- maybe i can provide a builtin SRTP mapper too, so already ready to use

i dont like to add a reference to FCS just for the projectcracker type (anyway is really dumb data).

I'll do that @alfonsogarciacaro so you dont need that file anymore (so less moving bugfixes around).
added to backlog

**Comment by enricosada** [comment]
sry @alfonsogarciacaro didnt see before the issue

**Comment by alfonsogarciacaro** [comment]
No worries, I just wanted to ping you because the notification might have gone unnoticed :)

It'd be really helpful if you could add the features to the library, thank you! But I agree you shouldn't add the FCS dependency just for the type. For me, it'd be enough to have an interface with the same properties and I can do the conversion in my code :)
