### ISSUE TITLE
Passed additional MSBuildProperties seem to be ignored

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ionide/dotnet-proj-info#18]
I call [this method](https://github.com/fable-compiler/Fable/blob/422dd84df98361b50ed277c99a15cd2a811518c3/src/dotnet/Fable.Compiler/CLI/ProjectCoreCracker.fs#L55) as follows:

```projInfo ["DefineConstants", "FABLE_COMPILER"] file```

However, when parsing a project like the one below I don't get the `Thoth.Json.fsproj` project reference as expected, but `Thoth.Json.Net.fsproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <FableCompiler>$(DefineConstants.Contains('FABLE_COMPILER'))</FableCompiler>
  </PropertyGroup>
  <Choose>
    <When Condition="$(DefineConstants.Contains('FABLE_COMPILER'))">
        <ItemGroup>
            <ProjectReference Include="../src/Thoth.Json/Thoth.Json.fsproj" />
        </ItemGroup>
    </When>
    <Otherwise>
        <ItemGroup>
            <ProjectReference Include="../src/Thoth.Json.Net/Thoth.Json.Net.fsproj" />
        </ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
    <Compile Include="Util.fs" />
    <Compile Include="Tests.Json.Decode.fs" />
    <Compile Include="Tests.Json.Encode.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by Krzysztof-Cieslak** [comment]
This should work now after #88

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot @Krzysztof-Cieslak!

**Comment by NickDarvey** [comment]
@alfonsogarciacaro, I'm trying to do something near identical to your example. Is this expected to work now with fable >= 3.2.12?

**Comment by alfonsogarciacaro** [comment]
TBH, I'm not sure 😅 It may work for your App project, but it won't if you want to publish a Fable package because in that case Fable makes a simple XML parsing of the .fsproj file instead of calling MSBuild through Dotnet.ProjInfo.
