### ISSUE TITLE
Include netstandard reference in script file

### ISSUE THREAD

**Issue by nojaf** [ionide/dotnet-proj-info#36]
When using `fsxBinder.GetProjectOptionsFromScriptBy(tfm, scriptFile, input)` from #32 I would like to include a reference to `netstandard2.0` (needed for Fable).

Any ideas how I could do this?
My current workaround looks like this

```fsharp
#r @"C:\Users\nojaf\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\netstandard.dll"
#load @".paket\load\netstandard2.0\main.group.fsx"

open Fable.Helpers.React
open Fable.Import

let view = div [] [str "works"]

ReactDom.render(view, Browser.document.getElementById "app")
```

**Comment by enricosada** [comment]
It's not so easy, it's not possibile to guess the path to that reference.

The `netstandard.dll` must be resolved from a nupkg, so mean or `PackageReference` (paket or normal) or `Reference`
the former is not supported by fsi, so only `#r` is avaiable and that need a specific path.

And maybe it need other assemblies to works too, not just `netstandard.dll`

let me think about it.

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed with all the @baronfel's FSI resolution code we ported from FSAC. Check the new API in https://github.com/ionide/dotnet-proj-info/blob/master/src/Ionide.ProjInfo.ProjectSystem/FSIRefs.fs
