### ISSUE TITLE
Dotnet.ProjInfo.Inspect.getProjectInfo question

### ISSUE THREAD

**Issue by ncave** [ionide/dotnet-proj-info#72]
Not really a bug, just a quick question:
- #66 introduced a change in `Dotnet.ProjInfo.Inspect.getProjectInfo` which removes the `additionalArgs` parameter. Should client repos (`dotnet/fsharp`, `FCS`, `Fable`, etc.) just adapt to it when they switch to the latest version of the `Dotnet.ProjInfo` package, or should a dummy parameter be added back so it's backwards-compatible?

**Comment by Krzysztof-Cieslak** [comment]
My assumption here is that `dotnet-proj-info` is pre 1.0 version, and breaking changes in API may happen. After things are stabilized for 1.0 we will follow typical semantic versioning rules.
