### ISSUE TITLE
Investigate using stable paths for generated .targets and .props files

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/dotnet-proj-info#76]
This should hopefully enable internal MsBuild caching and improve performance.

CC: @TheAngryByrd

**Comment by TheAngryByrd** [comment]
I looked a bit into this and now with the single call to `dotnet msbuild` and additional flags like `DesignTimeBuild` and `SkipCompilerExecution`, having the same file or using another generated one seems to make no noticeable difference.
