### ISSUE TITLE
/p: DesignTimeBuild=true needed to get perf for project queries

### ISSUE THREAD

**Issue by dsyme** [ionide/dotnet-proj-info#81]
Hi all

I using this library to get project properties like OutputPath, IsPackable etc. for projects in https://github.com/fsprojects/FSharp.Formatting/pull/528

I was surprised how long each call to get these properties is taking, I'm seeing 5-10sec runtime for each project.  It seems the projects are actually building, because there are processes `fsc.exe` executing, which surprises me, I can't understand why a build would be happening given we have `/t:_Inspect_GetProperties` (there is nothing unusual about the project files)

I guess I'm just wondering if this is expected or if it's driver error?

The basics of what I'm doing appears to be the same as FsAutoComplete, without the caching.  The `msbuild`/`dotnet build` calls being generated are:

```
args = ["msbuild";
 "E:\GitHub\dsyme\FSharp.Formatting\tests\FSharp.CodeFormat.Tests\FSharp.CodeFormat.Tests.fsproj";
 "/t:_Inspect_GetProperties";
 "/p:_Inspect_GetProperties_OutFile=C:\Users\dsyme\AppData\Local\Temp\tmp2C34.tmp.GetProperties.txt";
 "/p:CustomAfterMicrosoftCommonTargets=C:\Users\dsyme\AppData\Local\Temp\tmp2C44.tmp.proj-info.hook.targets";
 "/p:CustomAfterMicrosoftCommonCrossTargetingTargets=C:\Users\dsyme\AppData\Local\Temp\tmp2C44.tmp.proj-info.hook.targets";
 "/nologo"; "/verbosity:quiet"]
```
Here's the outline of my code - the key thing is `Dotnet.ProjInfo.Inspect.msbuild msbuildPath runCmd` with the above arguments
```
        let additionalInfo =
            [ "OutputType"
              "IsTestProject"
              "IsPackable"
            ]
        let gp () = Dotnet.ProjInfo.Inspect.getProperties (["TargetPath"] @ additionalInfo)

        let loggedMessages = System.Collections.Concurrent.ConcurrentQueue<string>()
        let runCmd exePath args =
           printfn "args = %A" args
           runProcess loggedMessages.Enqueue slnDir exePath (args |> String.concat " ")
        let msbuildPath = Dotnet.ProjInfo.Inspect.MSBuildExePath.DotnetMsbuild "dotnet"
        let msbuildExec = Dotnet.ProjInfo.Inspect.msbuild msbuildPath runCmd

        let result = file |> Dotnet.ProjInfo.Inspect.getProjectInfos loggedMessages.Enqueue msbuildExec [gp] []
```

**Comment by Krzysztof-Cieslak** [comment]
Try adding `/bl` argument the list of arguments and then inspect generated binlog file with https://msbuildlog.com/. It should include all timings and detailed log of operations

**Comment by dsyme** [comment]
Ok thanks, will do.  

So I'm right in assuming that the intent of `Dotnet.ProjInfo.Inspect.getProperties ` and friends is that they not actually build the project? 

I actually might switch to unzipping a nuget package to get the actual packaged DLLs (in order to determine what we generate API docs for).

**Comment by Krzysztof-Cieslak** [comment]
Oh, I’ve just realized you’re not using any of the predefined set of targets, but rather getProperties directly. In such case you’ll probably need to enable Design Time Build by adding also `/p: DesignTimeBuild=true`

Normally (in FSAC/Ionide) we use higher level API (for getting all project info we need) and Design Time Build is enabled by one of the target&properties sets we use there internally

TBF it’s probably bug in how things are layered - we should always run in Design Time Build

**Comment by dsyme** [comment]
Ah that makes sense. I'll try with that

Also note I duplicated out your solution file parser since all I wanted was the list of projects.  I'll try to submit a PR to expose the solution file parser in an API?  Or at least something to get the loaded project order list?
