### ISSUE TITLE
multi-line property values like Description cause errors

### ISSUE THREAD

**Issue by dsyme** [ionide/dotnet-proj-info#82]
This is a note of an incompleteness: using `getProperties` with multi-line property values doesn't work correctly.  The error messages that result can be fairly obscure.

An example of a property value that causes problems: 
```
    <Description>
      The package is a collection of libraries that can be used for literate programming
      with F# (great for building documentation) and for generating library documentation
      from inline code comments. The key componments are Markdown parser, tools for formatting
      F# code snippets, including tool tip type information and a tool for generating
      documentation from library metadata.
    </Description>
```

**Comment by Krzysztof-Cieslak** [comment]
The bug is probably somewhere in this function - https://github.com/ionide/dotnet-proj-info/blob/master/src/Dotnet.ProjInfo/Inspect.fs#L252
